name: demo
channels:
    - conda-forge
dependencies:
    - python=3.6
    - scikit-learn
    - statsmodels
    - numpy
    - pandas
    - jupyter
    - notebook
    - mkl-service
    - seaborn
    - theano
    - pymc3